services:
  - type: web
    name: youtube-bot
    runtime: python
    rootDir: bots/youtube-bot
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SUPADATA_API_KEY
        sync: false
