# Maps common names, nicknames, abbreviations -> clean symbol + exchange
# Format: "user_input_lowercase": ("SYMBOL", "EXCHANGE")

SYMBOL_MAP = {
    # -- NSE Indices --
    "nifty":              ("NIFTY",      "NSE"),
    "nifty 50":           ("NIFTY",      "NSE"),
    "nifty50":            ("NIFTY",      "NSE"),
    "bank nifty":         ("BANKNIFTY",  "NSE"),
    "banknifty":          ("BANKNIFTY",  "NSE"),
    "nifty bank":         ("BANKNIFTY",  "NSE"),
    "sensex":             ("SENSEX",     "BSE"),
    "nifty it":           ("NIFTYIT",    "NSE"),
    "nifty pharma":       ("NIFTYPHARMA","NSE"),
    "nifty auto":         ("NIFTYAUTO",  "NSE"),
    "nifty fmcg":         ("NIFTYFMCG",  "NSE"),
    "finnifty":           ("FINNIFTY",   "NSE"),
    "nifty fin":          ("FINNIFTY",   "NSE"),
    "midcap nifty":       ("MIDCPNIFTY", "NSE"),

    # -- NSE Large Caps --
    "reliance":           ("RELIANCE",   "NSE"),
    "ril":                ("RELIANCE",   "NSE"),
    "tcs":                ("TCS",        "NSE"),
    "tata consultancy":   ("TCS",        "NSE"),
    "infosys":            ("INFY",       "NSE"),
    "infy":               ("INFY",       "NSE"),
    "wipro":              ("WIPRO",      "NSE"),
    "hcl":                ("HCLTECH",    "NSE"),
    "hcl tech":           ("HCLTECH",    "NSE"),
    "hcltech":            ("HCLTECH",    "NSE"),
    "hdfc bank":          ("HDFCBANK",   "NSE"),
    "hdfcbank":           ("HDFCBANK",   "NSE"),
    "hdfc":               ("HDFCBANK",   "NSE"),
    "icici bank":         ("ICICIBANK",  "NSE"),
    "icicibank":          ("ICICIBANK",  "NSE"),
    "icici":              ("ICICIBANK",  "NSE"),
    "sbi":                ("SBIN",       "NSE"),
    "state bank":         ("SBIN",       "NSE"),
    "axis bank":          ("AXISBANK",   "NSE"),
    "axisbank":           ("AXISBANK",   "NSE"),
    "kotak":              ("KOTAKBANK",  "NSE"),
    "kotak bank":         ("KOTAKBANK",  "NSE"),
    "kotakbank":          ("KOTAKBANK",  "NSE"),
    "bajaj finance":      ("BAJFINANCE", "NSE"),
    "bajfinance":         ("BAJFINANCE", "NSE"),
    "bajaj finserv":      ("BAJAJFINSV", "NSE"),
    "bajajfinsv":         ("BAJAJFINSV", "NSE"),
    "bharti airtel":      ("BHARTIARTL", "NSE"),
    "airtel":             ("BHARTIARTL", "NSE"),
    "bhartiartl":         ("BHARTIARTL", "NSE"),
    "ongc":               ("ONGC",       "NSE"),
    "ntpc":               ("NTPC",       "NSE"),
    "power grid":         ("POWERGRID",  "NSE"),
    "powergrid":          ("POWERGRID",  "NSE"),
    "ultratech":          ("ULTRACEMCO", "NSE"),
    "ultratech cement":   ("ULTRACEMCO", "NSE"),
    "ultracemco":         ("ULTRACEMCO", "NSE"),
    "asian paints":       ("ASIANPAINT", "NSE"),
    "asianpaint":         ("ASIANPAINT", "NSE"),
    "hindustan unilever": ("HINDUNILVR", "NSE"),
    "hul":                ("HINDUNILVR", "NSE"),
    "hindunilvr":         ("HINDUNILVR", "NSE"),
    "itc":                ("ITC",        "NSE"),
    "maruti":             ("MARUTI",     "NSE"),
    "maruti suzuki":      ("MARUTI",     "NSE"),
    "tata motors":        ("TATAMOTORS", "NSE"),
    "tatamotors":         ("TATAMOTORS", "NSE"),
    "tata steel":         ("TATASTEEL",  "NSE"),
    "tatasteel":          ("TATASTEEL",  "NSE"),
    "sun pharma":         ("SUNPHARMA",  "NSE"),
    "sunpharma":          ("SUNPHARMA",  "NSE"),
    "dr reddy":           ("DRREDDY",    "NSE"),
    "drreddy":            ("DRREDDY",    "NSE"),
    "cipla":              ("CIPLA",      "NSE"),
    "divis":              ("DIVISLAB",   "NSE"),
    "divislab":           ("DIVISLAB",   "NSE"),
    "adani ports":        ("ADANIPORTS", "NSE"),
    "adaniports":         ("ADANIPORTS", "NSE"),
    "adani enterprises":  ("ADANIENT",   "NSE"),
    "adanient":           ("ADANIENT",   "NSE"),
    "adani green":        ("ADANIGREEN", "NSE"),
    "adanigreen":         ("ADANIGREEN", "NSE"),
    "jsw steel":          ("JSWSTEEL",   "NSE"),
    "jswsteel":           ("JSWSTEEL",   "NSE"),
    "l&t":                ("LT",         "NSE"),
    "lt":                 ("LT",         "NSE"),
    "larsen":             ("LT",         "NSE"),
    "larsen toubro":      ("LT",         "NSE"),
    "m&m":                ("M&M",        "NSE"),
    "mahindra":           ("M&M",        "NSE"),
    "titan":              ("TITAN",      "NSE"),
    "nestle":             ("NESTLEIND",  "NSE"),
    "nestleind":          ("NESTLEIND",  "NSE"),
    "tech mahindra":      ("TECHM",      "NSE"),
    "techm":              ("TECHM",      "NSE"),
    "hindalco":           ("HINDALCO",   "NSE"),
    "sbi life":           ("SBILIFE",    "NSE"),
    "sbilife":            ("SBILIFE",    "NSE"),
    "hdfc life":          ("HDFCLIFE",   "NSE"),
    "hdfclife":           ("HDFCLIFE",   "NSE"),
    "bpcl":               ("BPCL",       "NSE"),
    "ioc":                ("IOC",        "NSE"),
    "indusind":           ("INDUSINDBK", "NSE"),
    "indusind bank":      ("INDUSINDBK", "NSE"),
    "indusindbk":         ("INDUSINDBK", "NSE"),
    "hero motocorp":      ("HEROMOTOCO", "NSE"),
    "hero":               ("HEROMOTOCO", "NSE"),
    "heromotoco":         ("HEROMOTOCO", "NSE"),
    "bajaj auto":         ("BAJAJ-AUTO", "NSE"),
    "bajajauto":          ("BAJAJ-AUTO", "NSE"),
    "eicher":             ("EICHERMOT",  "NSE"),
    "eicher motors":      ("EICHERMOT",  "NSE"),
    "eichermot":          ("EICHERMOT",  "NSE"),
    "zomato":             ("ZOMATO",     "NSE"),
    "paytm":              ("PAYTM",      "NSE"),
    "nykaa":              ("NYKAA",      "NSE"),
    "policybazaar":       ("POLICYBZR",  "NSE"),
    "policybzr":          ("POLICYBZR",  "NSE"),
    "dmart":              ("DMART",      "NSE"),
    "avenue supermarts":  ("DMART",      "NSE"),
    "trent":              ("TRENT",      "NSE"),
    "vedanta":            ("VEDL",       "NSE"),
    "vedl":               ("VEDL",       "NSE"),
    "coal india":         ("COALINDIA",  "NSE"),
    "coalindia":          ("COALINDIA",  "NSE"),
    "grasim":             ("GRASIM",     "NSE"),
    "shriram finance":    ("SHRIRAMFIN", "NSE"),
    "shriramfin":         ("SHRIRAMFIN", "NSE"),

    # -- MCX Commodities --
    "gold":               ("GOLD",       "MCX"),
    "silver":             ("SILVER",     "MCX"),
    "crude":              ("CRUDEOIL",   "MCX"),
    "crude oil":          ("CRUDEOIL",   "MCX"),
    "crudeoil":           ("CRUDEOIL",   "MCX"),
    "natural gas":        ("NATURALGAS", "MCX"),
    "natgas":             ("NATURALGAS", "MCX"),
    "ng":                 ("NATURALGAS", "MCX"),
    "copper":             ("COPPER",     "MCX"),
    "zinc":               ("ZINC",       "MCX"),
    "aluminium":          ("ALUMINIUM",  "MCX"),
    "nickel":             ("NICKEL",     "MCX"),
    "lead":               ("LEAD",       "MCX"),

    # -- Forex --
    "usdinr":             ("USDINR",     "FOREX"),
    "usd inr":            ("USDINR",     "FOREX"),
    "dollar":             ("USDINR",     "FOREX"),
    "eurinr":             ("EURINR",     "FOREX"),
    "eur inr":            ("EURINR",     "FOREX"),
    "gbpinr":             ("GBPINR",     "FOREX"),
    "gbp inr":            ("GBPINR",     "FOREX"),
    "jpyinr":             ("JPYINR",     "FOREX"),
    "jpy inr":            ("JPYINR",     "FOREX"),
    "eurusd":             ("EURUSD",     "FOREX"),
    "eur usd":            ("EURUSD",     "FOREX"),
    "gbpusd":             ("GBPUSD",     "FOREX"),
    "gbp usd":            ("GBPUSD",     "FOREX"),
    "usdjpy":             ("USDJPY",     "FOREX"),
    "usd jpy":            ("USDJPY",     "FOREX"),
}
